version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: agentdb
      POSTGRES_USER: agentuser
      POSTGRES_PASSWORD: agentpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
